// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Artist defines model for Artist.
type Artist struct {
	Albums      *int    `json:"albums,omitempty"`
	ArtistGenre *string `json:"artist_genre,omitempty"`
	ArtistName  *string `json:"artist_name,omitempty"`
	Username    string  `json:"username"`
}

// GetArtistListParams defines parameters for GetArtistList.
type GetArtistListParams struct {
	// Limit Limits the number of items on a page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Specifies the page number of the artists to be displayed
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}
